#!/usr/bin/env node
import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import process from "process";
import { builtinModules } from "node:module";
import sveltePreprocess from "svelte-preprocess";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const banner =
	"/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/\n";

export async function runPluginBuild(configUrl) {
	const pluginRoot = dirname(fileURLToPath(configUrl));
	const prod = process.argv[2] === "production";

	const ctx = await esbuild.context({
		banner: { js: banner },
		entryPoints: [join(pluginRoot, "src/main.ts")],
		plugins: [
			esbuildSvelte({
				preprocess: sveltePreprocess({ typescript: true }),
				compilerOptions: { css: "injected" },
			}),
		],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtinModules,
		],
		format: "cjs",
		target: "es2018",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: join(pluginRoot, "main.js"),
		minify: prod,
	});

	if (prod) {
		await ctx.rebuild();
		await ctx.dispose();
		process.exit(0);
	}
	await ctx.watch();
}
