#!/usr/bin/env node
/**
 * Merges packages/theme/tokens.css + packages/heatmap/heatmap.css + plugins/<name>/src/plugin.css
 * + packages/theme/people.css + packages/theme/shell.css [+ src/timer/plugin.css] → styles.css
 * Order: tokens → heatmap → plugin → people → shell → timer (timer last).
 * For Fulcrum, also emits src/generated/pluginStyles.ts for runtime CSS injection.
 * Run from plugin directory (cwd = plugin root).
 */
import { mkdirSync, readFileSync, unlinkSync, writeFileSync, existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const cwd = process.cwd();
const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const tokensPath = join(root, "packages/theme/tokens.css");
const heatmapPath = join(root, "packages/heatmap/heatmap.css");
const peoplePath = join(root, "packages/theme/people.css");
const shellPath = join(root, "packages/theme/shell.css");
const pluginCssPath = join(cwd, "src/plugin.css");
const timerCssPath = join(cwd, "src/timer/plugin.css");

const tokens = readFileSync(tokensPath, "utf8");
const heatmap = existsSync(heatmapPath) ? readFileSync(heatmapPath, "utf8") : "";
const pluginCss = existsSync(pluginCssPath) ? readFileSync(pluginCssPath, "utf8") : "";
const timerCss = existsSync(timerCssPath) ? readFileSync(timerCssPath, "utf8") : "";
const people = existsSync(peoplePath) ? readFileSync(peoplePath, "utf8") : "";
const shell = existsSync(shellPath) ? readFileSync(shellPath, "utf8") : "";
const combined = `${tokens}\n${heatmap}\n${pluginCss}\n${people}\n${shell}\n${timerCss}\n`;
const out = join(cwd, "styles.css");
writeFileSync(out, combined);
console.log(`Wrote ${out}`);

const timerOut = join(cwd, "timer-styles.css");
if (existsSync(timerOut)) {
	unlinkSync(timerOut);
}

if (timerCss && existsSync(join(cwd, "src/timer/TimerModule.ts"))) {
	const generatedDir = join(cwd, "src/generated");
	mkdirSync(generatedDir, { recursive: true });
	const generatedPath = join(generatedDir, "pluginStyles.ts");
	writeFileSync(
		generatedPath,
		`/** Generated by tooling/merge-css.mjs — do not edit */\nexport const FULCRUM_PLUGIN_CSS = ${JSON.stringify(combined)};\n`,
	);
	console.log(`Wrote ${generatedPath}`);
}
